# Generated by Django 5.2.4 on 2025-11-03 10:53

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_mode_message', models.CharField(blank=True, max_length=127)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
