# Generated by Django 5.2.3 on 2025-06-23 05:39

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOtp',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('otp_hash', models.CharField(max_length=1023, verbose_name='OTP Hash')),
                ('expiration_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'login OTP',
                'verbose_name_plural': 'login OTPs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('UNSET', 'Unset'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee')], default='UNSET', max_length=15)),
                ('username', models.CharField(max_length=63, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(blank=True, max_length=31)),
                ('last_name', models.CharField(blank=True, max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='This is required for customers.', max_length=128, null=True, region=None)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=7)),
                ('nic_number', models.CharField(blank=True, max_length=31, verbose_name='NIC/ID number')),
                ('address_line1', models.CharField(blank=True, max_length=127, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=127, verbose_name='address line 2')),
                ('address_city', models.CharField(blank=True, max_length=127, verbose_name='city')),
                ('address_state', models.CharField(blank=True, max_length=127, verbose_name='state/province')),
                ('address_zip', models.CharField(blank=True, max_length=31, verbose_name='zip/postal code')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=127, verbose_name='emergency contact name')),
                ('emergency_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='emergency contact phone')),
                ('recent_surgery', models.BooleanField(default=False, verbose_name='recent surgery')),
                ('recent_surgery_notes', models.TextField(blank=True, verbose_name='recent surgery notes')),
                ('health_complications', models.BooleanField(default=False, verbose_name='health complications')),
                ('health_complications_notes', models.TextField(blank=True, verbose_name='health complications notes')),
                ('emp_organization', models.ForeignKey(blank=True, help_text='This is only required for employees.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEnrollment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_enrollments', to='organizations.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_enrollments_cus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrolled branch (customer)',
                'verbose_name_plural': 'enrolled branches (customer)',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='unique_branch_user_customer')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEnrollment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_enrollments', to='organizations.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_enrollments_emp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrolled branch (employee)',
                'verbose_name_plural': 'enrolled branches (employee)',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='unique_branch_user_employee')],
            },
        ),
    ]
