# Generated by Django 5.2.3 on 2025-06-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_role',
            field=models.CharField(choices=[('BRANCH_ADMIN', 'Branch Admin'), ('ORG_ADMIN', 'Org Admin')], default='BRANCH_ADMIN', max_length=15),
        ),
    ]
