# Generated by Django 5.2.3 on 2025-07-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerenrollment_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenrollment',
            name='sn',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
