# Generated by Django 5.2.4 on 2025-07-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customerenrollment_sn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOtp',
        ),
    ]
