# Generated by Django 5.2.4 on 2025-07-30 09:21

from django.db import migrations, models


def populate_customer_sn(apps, schema_editor):
    customer = apps.get_model("users", "CustomerEnrollment")
    for customer in customer.objects.all():
        customer.customer_sn = f"{customer.branch.organization.code}/{customer.branch.code}/{customer.sn:04d}"
        customer.save(update_fields=["customer_sn"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_loginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerenrollment",
            name="customer_sn",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(populate_customer_sn, reverse_code=migrations.RunPython.noop),
    ]
