# Generated by Django 5.2.4 on 2025-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customerenrollment_customer_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('UNSET', 'Unset'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee'), ('COACH', 'Coach')], default='UNSET', max_length=15),
        ),
    ]
