# Generated by Django 5.2.4 on 2025-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_heading',
            field=models.CharField(blank=True, choices=[('PERSONAL_TRAINER', 'Personal Trainer'), ('FITNESS_COACH', 'Fitness Coach'), ('STRENGTH_CONDITIONING_COACH', 'Strength & Conditioning Coach'), ('GYM_INSTRUCTOR', 'Gym Instructor'), ('GROUP_FITNESS_INSTRUCTOR', 'Group Fitness Instructor'), ('EXERCISE_SPECIALIST', 'Exercise Specialist')], max_length=30),
        ),
    ]
