# Generated by Django 5.2.4 on 2025-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_cover_photo_user_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_cover_photos/'),
        ),
    ]
