# Generated by Django 5.2.4 on 2025-09-30 04:17

from django.db import migrations, models


def update_coach_users_to_employee(apps, schema_editor):
    """Update all existing COACH users to EMPLOYEE type."""
    user_model = apps.get_model('users', 'User')
    user_model.objects.filter(user_type='COACH').update(user_type='EMPLOYEE')


def reverse_update_coach_users_to_employee(apps, schema_editor):
    """Reverse operation - update EMPLOYEE users back to COACH (if needed)."""
    # Note: This reverse operation is not precise since we can't distinguish
    # which employees were originally coaches vs regular employees.
    # In production, you might want to create a backup or add additional logic.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_cover_photo'),
    ]

    operations = [
        # First, update existing COACH users to EMPLOYEE
        migrations.RunPython(
            update_coach_users_to_employee,
            reverse_update_coach_users_to_employee,
        ),
        # Then, alter the field to remove COACH from choices
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('UNSET', 'Unset'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee')], default='UNSET', max_length=15),
        ),
    ]
