# Generated by Django 5.2.4 on 2025-10-10 07:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_merge_20250916_1332'),
        ('users', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_role',
            field=models.CharField(choices=[('BRANCH_ADMIN', 'Branch Admin'), ('ORG_ADMIN', 'Org Admin')], default='BRANCH_ADMIN', help_text='This is only required for employees.', max_length=15),
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the permission level', max_length=100)),
                ('coach_access', models.BooleanField(default=False, help_text='Grants access to coach-specific features')),
                ('dashboard_financial_access', models.BooleanField(default=False, help_text='Grants access to financial dashboard features')),
                ('organization', models.ForeignKey(help_text='Organization this permission belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='emp_permission',
            field=models.ForeignKey(blank=True, help_text='This is only required for employees.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.employeepermission'),
        ),
        migrations.AddConstraint(
            model_name='employeepermission',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_organization_permission_name'),
        ),
    ]
