FROM python:3.11-slim

# Install system dependencies
RUN apt update && apt --no-install-recommends install -y \
    build-essential libpq-dev gettext \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Create a non-root user
RUN adduser --disabled-password --gecos '' appuser

# Install packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Add scripts
COPY tools/infra/entrypoint.sh entrypoint.sh
COPY tools/infra/gunicorn.conf.py gunicorn.conf.py
RUN chmod +x entrypoint.sh

# Copy project files
COPY ./apps apps
COPY ./config config
COPY ./static static
COPY ./templates templates
COPY manage.py .

# Change ownership and switch to non-root user
RUN chown -R appuser /app
USER appuser

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
